<?php
/* 
 * Generated by Webdimensions
 * www.webdimensions.co.in
 */
 
class Amazon_report_request_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get amazon_report_request_log by ID_ACCOUNT
     */
    function get_amazon_report_request_log($ID_ACCOUNT)
    {
        return $this->db->get_where('feedback_settings',array('ID_ACCOUNT'=>$ID_ACCOUNT))->row_array();
    }
    
    /*
     * Get all amazon_report_request_log
     */
    function get_all_amazon_report_request_log()
    {
        return $this->db->get('feedback_settings')->result_array();
    }
    
    /*
     * function to add new amazon_report_log
     */
    function add_amazon_report_request_log($params)
    {
        $this->db->insert('amazon_reportrequestlog',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update amazon_report_request_log
     */
    function update_amazon_report_request_log($ID_ACCOUNT,$params)
    {
        $this->db->where('ID_ACCOUNT',$ID_ACCOUNT);
        $this->db->update('amazon_reportrequestlog',$params);
    }
    
    function custom_where_update_amazon_report_request_log($wherecondition,$params)
    {
        $this->db->where($wherecondition);
        $this->db->update('amazon_reportrequestlog',$params);
    }
    
    /*
     * function to delete amazon_report_request_log
     */
    function delete_amazon_report_request_log($ID_ACCOUNT)
    {
        $this->db->delete('feedback_settings',array('ID_ACCOUNT'=>$ID_ACCOUNT));
    }
    
    function get_log_result($wherecondition){
        $logResult = $this->db->get_where('amazon_reportrequestlog', $wherecondition);
        return $logResult->row();
    }
}
