<?php
/* 
 * Generated by Webdimensions 
 * www.webdimensions.co.in
 */
 
class Amazon_api_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get amazon_api_log by ID_ACCOUNT
     */
    function get_amazon_api_log($ID_ACCOUNT)
    {
        return $this->db->get_where('feedback_settings',array('ID_ACCOUNT'=>$ID_ACCOUNT))->row_array();
    }
    
    /*
     * Get all amazon_api_log
     */
    function get_all_amazon_api_log()
    {
        return $this->db->get('feedback_settings')->result_array();
    }
    
    /*
     * function to add new amazon_report_log
     */
    function add_amazon_api_log($accountID, $params)
    {
        $t = time();
	    $this->db->query("INSERT INTO amazonapi_log(ID_ACCOUNT,apidate,task) VALUES ($accountID,$t,'$params')");
//        $this->db->insert('amazonapi_log',$params);
//        return $this->db->insert_id();
    }
    
    /*
     * function to update amazon_api_log
     */
    function update_amazon_report_log($ID_ACCOUNT,$params)
    {
        $this->db->where('ID_ACCOUNT',$ID_ACCOUNT);
        $this->db->update('amazon_reportrequestlog',$params);
    }
    
    function custom_where_update_amazon_api_log($wherecondition,$params)
    {
        $this->db->where($wherecondition);
        $this->db->update('amazon_reportrequestlog',$params);
    }
    
    /*
     * function to delete amazon_api_log
     */
    function delete_amazon_api_log($ID_ACCOUNT)
    {
        $this->db->delete('feedback_settings',array('ID_ACCOUNT'=>$ID_ACCOUNT));
    }
    
    function get_log_result($ID_ACCOUNT){
        $logResult = $this->db->query("SELECT requestid,ID_LOG FROM  amazon_reportrequestlog WHERE status != 2 and reporttype = '_GET_FLAT_FILE_ORDERS_DATA_' AND ID_ACCOUNT = " . $ID_ACCOUNT);
        return $logResult;
    }
}
