<?php

/*
 * Generated by Webdimensions
 * www.webdimensions.co.in
 */

class Case_log_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }

    public function addcaselog($data)
    {
        $this->db->insert("case_log",$data);
        return $this->db->insert_id();
    }
}