<?php
/*
 * Generated by Webdimensions
 * www.webdimensions.co.in
 */

class Fba_inventory_model extends CI_Model
{

    function __construct()
    {
        parent::__construct();
    }


    function custom_count_fba_inventory($params)
    {
        $countTotal = $this->db->get_where('fba_inventory', $params);
        return $countTotal->num_rows();
    }

    function insert_fba_inventory($params) {
        $this->db->insert('fba_inventory', $params);
        return $this->db->insert_id();
    }

}