<?php

/*
 * Generated by Webdimensions
 * www.webdimensions.co.in
 */

class Feedback_asin_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get feedback_asin by ID_ACCOUNT
     */

    function get_feedback_asin($ID_ACCOUNT) {
        return $this->db->get_where('feedback_asin', array('ID_ACCOUNT' => $ID_ACCOUNT))->row_array();
    }

    /*
     * Get all feedback_asin
     */

    function get_all_feedback_asin() {
        return $this->db->get('feedback_asin')->result_array();
    }

    /*
     * function to add new feedback_asin
     */

    function add_feedback_asin($ID_ACCOUNT, $sku, $marketplaceid, $asin) {
        $this->db->query("INSERT IGNORE INTO feedback_asin (ID_ACCOUNT,sku,amazonasin,mws_marketplaceid) VALUES (" . $ID_ACCOUNT . ",'$sku'," . "'$asin','" . $marketplaceid . "')");
        return $this->db->insert_id();
    }

    /*
     * function to update feedback_asin
     */

    function update_feedback_asin($ID_ACCOUNT, $params) {
        $this->db->where('ID_ACCOUNT', $ID_ACCOUNT);
        $this->db->update('feedback_asin', $params);
    }

    /*
     * function to delete feedback_asin
     */

    function delete_feedback_asin($ID_ACCOUNT) {
        $this->db->delete('feedback_asin', array('ID_ACCOUNT' => $ID_ACCOUNT));
    }

}
