<?php

/*
 * Generated by Webdimensions
 * www.webdimensions.co.in
 */

class Feedback_order_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get feedback_setting by ID_ACCOUNT
     */

    function get_feedback_setting()
    {
        $t = time();
        $last24hours = $t - (1 * 24 * 60 * 60);
        $result = $this->db->query("
	SELECT a.ID_ACCOUNT, s.mws_sellerid, s.mws_authtoken, s.loadedfirstorderdata, s.amazonstorename,s.importorderdays,
        d.marketplace_id, d.access_key, d.secret_key, m.marketplace_id, m.host, m.id
        FROM accounts AS a, feedback_settings AS s, dev_accounts AS d, marketplaces AS m
	WHERE m.id= d.marketplace_id AND s.mws_marketplaceid = m.id AND s.ID_ACCOUNT = a.ID_ACCOUNT  and s.apiactive = 1 AND a.removed = 0 AND a.enabled = 1 and a.deleted='0' AND s.hourlimit_orderdata < 6 AND (s.api_orderdatadate  = 0 OR s.api_orderdatadate < $last24hours)
        ");
        return $result;
    }

    /*
     * Get feedback_setting by ID_ACCOUNT
     */

    function add_feedback_order($params) {
        $this->db->insert('feedback_orders', $params);
        return $this->db->insert_id();
    }

    /*
     * Get feedback_order count by ID_ACCOUNT
     */

    function custom_count_feedback_order($params) {


        $countTotal = $this->db->get_where('feedback_orders', $params);
        return $countTotal->num_rows();
    }

    /*
     * update amazone order
     */

    function custom_where_update_amazon_order($wherecondition, $params) {
        $this->db->where($wherecondition);
        $this->db->update('feedback_orders', $params);
    }

    /*
     * Get order by account_id
     */

    function get_order_by_account_id($accountid) {
        $this->db->where('ID_ACCOUNT', $accountid);
        return $this->db->get('feedback_orders')->result_array();
    }

    /*
     * Get order coutnt by account_id
     */

    public function get_total_orders_count_by_accountid($accountid) {

        $this->db->select('SQL_CALC_FOUND_ROWS null as rows', false);
        $this->db->where('ID_ACCOUNT', $accountid);
        $qyery = $this->db->get('feedback_orders');
        $total = $this->db->query('SELECT FOUND_ROWS() count;')->row()->count;
        return $total;
    }

}
