<?php

/* Generated by Webdimensions  www.webdimensions.co.in */

class Generate_Never_return_case extends CI_controller
{

    function __construct()
    {
        parent::__construct();
        if (!$this->input->is_cli_request())
        {
            show_404();
        }
        $this->load->library('amazon');
        $this->load->model("user_model");
        $this->load->model("reimbursement_model");
        $this->load->model("Case_log_model");
        $this->load->library('rat');
        $this->logging = new Rat();
    }

    public function index()
    {
        $cronName = "Order Never Return";
        $content = date("d-m-Y H:i:s") . " " . "Order Never Return case Start";
        $this->logging->write_log($cronName, $content, 1, 0);
        $allUsers = $this->user_model->getAllActiveUsers();
        foreach ($allUsers as $user)
        {
            $arrCaseID = array();
            $allRecordsFetched = $this->reimbursement_model->gethistorycronstatusbyaccountid($user['ID_ACCOUNT']);

            if (!empty($allRecordsFetched))
            {
                if($allRecordsFetched['FinanceRefundStatus'] == 1 && $allRecordsFetched['ReimburseStatus'] == 1 && $allRecordsFetched['OrderReturnStatus'] == 1 && $allRecordsFetched['OrderStatus'] == 1)
                {
                    $allpaymentDetails = $this->reimbursement_model->getPaymentDetails($user['ID_ACCOUNT']);
                    foreach ($allpaymentDetails as $key => $record)
                    {
                        if ($record['ID_ACCOUNT'] == $user['ID_ACCOUNT'])
                        {
                            $time = strtotime($record['date']);
                            $currentDate = date('Y-m-d H:i:s');
                            $CurrentDate45 = date('Y-m-d H:i:s', mktime(date("h", $time), date("i", $time), date("s", $time), date("m", $time), date("d", $time) + 50, date("Y", $time)));
                            if($CurrentDate45 < $currentDate)
                            {
                                $reimbursementDetails = $this->reimbursement_model->getReimbursementDetailsByOrderId($record['order_id'], $user['ID_ACCOUNT']);
                                $customerReturnDetails = $this->reimbursement_model->getReturnCustomerOrderDetailsNew($record['order_id']);
                                $checkorderID = $this->reimbursement_model->checkorderId($record['order_id'], $user['ID_ACCOUNT']);


                                if (empty($customerReturnDetails) && empty($reimbursementDetails) && !empty($checkorderID))
                                {
                                    $t = time();
                                    $data = array('case_type' => 'ONR', 'status' => '1');
                                    $effectedRow = $this->reimbursement_model->updatePaymentwithCORtype($data, $record['id']);
                                    if ($record['amount'] < 0)
                                    {
                                        $data = array('ID_ACCOUNT' => $record['ID_ACCOUNT'], 'order_id' => $record['order_id'], 'status' => '0', 'case_type' => 'ONR', 'date' => date('Y-m-d h:i:s'));
                                        $insertId = $this->reimbursement_model->insertCaseId($data);
                                        $log_data = array('ID_ACCOUNT' => $user['ID_ACCOUNT'], 'case_type' => 'ONR', 'inventory_order_id' => $record['order_id'], 'timestamp' => $t);
                                    }
                                    $arrCaseID[] = $this->Case_log_model->addcaselog($log_data);
                                }
                            }
                        }
                    }
                    if (!empty($arrCaseID))
                    {
                        $strCases = implode(",", $arrCaseID);
                        $content = "Generated Cases :" . $strCases;
                        $this->logging->write_log($cronName, $content, 2, $user['ID_ACCOUNT']);
                    }
                }
            }
        }
        $content = date("d-m-Y H:i:s") . " " . "Order Never Return case End";
        $this->logging->write_log($cronName, $content, 3, 0);
    }
}
