<?php

/* Generated by Webdimensions  www.webdimensions.co.in */

class Generate_Inventory_loss_case_historical extends CI_controller
{

    function __construct()
    {
        parent::__construct();
        if (!$this->input->is_cli_request()) {
            show_404();
        }
        $this->load->library('amazon');
        $this->load->model("user_model");
        $this->load->model("reimbursement_model");
        $this->load->model("inventory_salvager_model");
        $this->load->model("Inventory_salvager_model_historical");
        $this->load->model("Case_log_model");
        $this->load->library('rat');
        $this->logging = new Rat();
    }

    public function index()
    {
        $cronName = "Generate Loss Inventory Case Historical";
        $content = date("d-m-Y H:i:s") . " " . "Generate Loss Inventory case Historical cron Start";
        $this->logging->write_log($cronName, $content, 1, 0);
        $inventoryCaseRecord = array();
        $allUsers = $this->user_model->getAllActiveUsers();
        foreach ($allUsers as $user)
        {
            $allRecordsFetched = $this->reimbursement_model->gethistorycronstatusbyaccountid($user['ID_ACCOUNT']);
            $historicalRecordCheck = $this->user_model->gethistoricalrecordcheck( $user['ID_ACCOUNT'] );
            if ( $historicalRecordCheck['setinventoryhistorical'] == 1 )
            {
                if ( ! empty( $allRecordsFetched ) )
                {
                    if ( $allRecordsFetched['InventoryStatus'] == 1 && $allRecordsFetched['ReimburseStatus'] == 1 )
                    {
                        $alllossInventoryCounts = $this->Inventory_salvager_model_historical->getalllostInventoryCount( $user['ID_ACCOUNT']);
                        foreach ( $alllossInventoryCounts as $lossInventory )
                        {
                            $allfoundInventoryCount = $this->Inventory_salvager_model_historical->getallfoundInventoryCount( $user['ID_ACCOUNT'], $lossInventory['fnsku'] );
                            if ( $allfoundInventoryCount )
                            {
                                $lossInventoryDetails  = $this->Inventory_salvager_model_historical->getalllostInventoryDetails( $user['ID_ACCOUNT'], $lossInventory['fnsku'] );
                                $foundInventoryDetails = $this->Inventory_salvager_model_historical->getallfoundInventoryDetail( $user['ID_ACCOUNT'], $lossInventory['fnsku'] );
                                if ( abs( $lossInventory['TotalQty'] ) > $allfoundInventoryCount['TotalFoundQty'] )
                                {
                                    $remainingLossInventory  = $lossInventory['TotalQty'] + $allfoundInventoryCount['TotalFoundQty'];
                                    $reimburseInventoryCount = $this->Inventory_salvager_model_historical->getallReimbursementCount( $user['ID_ACCOUNT'], $lossInventory['fnsku'] );
                                    if ( $reimburseInventoryCount['TotalReimbursementQty'] )
                                    {
                                        $reimburseInventoryDetails = $this->Inventory_salvager_model_historical->getallReimbursementDetail( $user['ID_ACCOUNT'], $lossInventory['fnsku'] );
                                        if ( $remainingLossInventory > $reimburseInventoryCount['TotalReimbursementQty'] )
                                        {
                                            $generatecaseLostInventory = $remainingLossInventory + $reimburseInventoryCount['TotalReimbursementQty'];
                                            $this->generatecaseUpdatelostinventory( $generatecaseLostInventory, $lossInventoryDetails);
                                            $this->updatereimbursedetail( $reimburseInventoryCount['TotalReimbursementQty'], $reimburseInventoryCount['TotalReimbursementQty'], $reimburseInventoryDetails );
                                        }
                                        else
                                        {
                                            $remainingReimbuirsementInventory = $reimburseInventoryCount['TotalReimbursementQty'] + $remainingLossInventory;
                                            $generatecaseLostInventory        = 0;
                                            $this->updatereimbursedetail( $remainingReimbuirsementInventory, $reimburseInventoryCount['TotalReimbursementQty'], $reimburseInventoryDetails );
                                            $this->generatecaseUpdatelostinventory( $generatecaseLostInventory, $lossInventoryDetails);
                                        }
                                    }
                                    else
                                    {
                                        $this->updatefoundinventory( '0', $allfoundInventoryCount['TotalFoundQty'], $foundInventoryDetails );
                                        $this->generatecaseUpdatelostinventory( $remainingLossInventory, $lossInventoryDetails);
                                    }
                                }
                                else
                                {
                                    $remainingfoundInventory = $lossInventory['TotalQty'] + $allfoundInventoryCount['TotalFoundQty'];
                                    $this->updatefoundinventory( $remainingfoundInventory, $allfoundInventoryCount['TotalFoundQty'], $foundInventoryDetails );
                                    $this->generatecaseUpdatelostinventory( '0', $lossInventoryDetails);
                                }
                            }
                        }
                    }
                }
                $historicalRecordUpdate = $historicalRecordCheck['setinventoryhistorical'] + 1;
                $setHistoricalrecord    = array( 'setinventoryhistorical' => $historicalRecordUpdate );
                $this->user_model->sethistoricalrecord( $setHistoricalrecord, $user['ID_ACCOUNT'] );
            }
        }
        $content = date("d-m-Y H:i:s") . " " . "Generate Loss Inventory Case Historical cron End";
        $this->logging->write_log($cronName, $content, 3, 0);
    }

    public function generatecaseUpdatelostinventory($generatecaseLostInventory, $lossInventoryDetails)
    {
        $arrCaseID = array();
        echo "GenerateInventorycase";
        $cronName = "Generate Missing Found Inventory Case";
        foreach ($lossInventoryDetails as $index => $lostInventory) {
            if ($index < abs($generatecaseLostInventory)) {
                $start_date = date( 'Y-m-d 0:0:0', strtotime( date( 'Y-m' ) . " -17 month" ) );
                $end_date   = date( 'Y-m-d 23:59:59', strtotime( "-1 day" ) );
                $casetype = 'ULFW';
                $caseDetail = array(
                    'accountId' => $lostInventory['ID_ACCOUNT'],
                    'inventoryItemId' => $lostInventory['transaction_item_id'],
                    'date' => date('Y-m-d H:i:s'),
                    'report_start_date' => $start_date,
                    'report_end_date' => $end_date
                );
                echo "<pre />"; print_r($caseDetail);
                $t = time();
                $this->Inventory_salvager_model_historical->insertCaseId($caseDetail);
                $log_data = array('ID_ACCOUNT' => $lostInventory['ID_ACCOUNT'], 'case_type' => $casetype, 'inventory_order_id' => $lostInventory['transaction_item_id'], 'timestamp' => $t);
                $arrCaseID[] = $this->Case_log_model->addcaselog($log_data);
                $data = array('status' => '1', 'case_type' => $casetype);
                $this->Inventory_salvager_model_historical->updateInventoryDetailsData($data, $lostInventory['transaction_item_id'], $lostInventory['ID_ACCOUNT']);
            }
            else
            {
                $data = array('status' => '1');
                $this->Inventory_salvager_model_historical->updateInventoryDetailsData($data, $lostInventory['transaction_item_id'], $lostInventory['ID_ACCOUNT']);
            }
            if (!empty($arrCaseID))
            {
                $strCases = implode(",", $arrCaseID);
                $content = "Generated Inventory Cases :" . $strCases;
                $this->logging->write_log($cronName, $content, 2, $lostInventory['ID_ACCOUNT']);
            }
        }
    }

    public function updatefoundinventory($foundInventory= '', $foundInventoryCount, $foundInventoryDetails)
    {
        $foundInventoryCount = $foundInventoryCount-1;
        if ($foundInventory == '')
            $foundInventory = 0;
        while($foundInventoryCount >= $foundInventory)
        {
            echo "updateInventoryFound";
            $this->Inventory_salvager_model_historical->updatefoundDetailsById($foundInventoryDetails[$foundInventoryCount]['id']);
            $foundInventoryCount--;
        }
    }

    public function updatereimbursedetail($remainingReimbuirsementInventory = '', $reimburseInventoryCount, $reimburseInventoryDetails)
    {
        if ($remainingReimbuirsementInventory == '')
            $remainingReimbuirsementInventory = 0;
        while ($reimburseInventoryCount >= $remainingReimbuirsementInventory) {
            echo "updateInventoryReimbursement";
            $this->Inventory_salvager_model_historical->updateReimburseDetailsById($reimburseInventoryDetails[$reimburseInventoryCount]['id']);
            $reimburseInventoryCount--;
        }
    }
}